# Generated by Django 4.2.6 on 2024-05-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='notes',
            field=models.CharField(max_length=128),
        ),
    ]
