# Generated by Django 5.0.6 on 2024-05-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('score', '0002_alter_student_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writtenexam',
            name='exam_back_page',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='writtenexam',
            name='exam_front_page',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
